import fs from 'fs';
import path from 'path';

async function fetchWordLists() {
  console.log('Fetching word lists from 3blue1brown / Wordle datasets...');
  try {
    const allowedRes = await fetch('https://raw.githubusercontent.com/3b1b/videos/master/_2022/wordle/data/allowed_words.txt');
    const possibleRes = await fetch('https://raw.githubusercontent.com/3b1b/videos/master/_2022/wordle/data/possible_words.txt');

    if (!allowedRes.ok || !possibleRes.ok) {
      throw new Error(`Failed to fetch from github. Status: allowed=${allowedRes.status}, possible=${possibleRes.status}`);
    }

    const allowedText = await allowedRes.text();
    const possibleText = await possibleRes.text();

    const allowedWords = allowedText
      .split('\n')
      .map(w => w.trim().toUpperCase())
      .filter(w => /^[A-Z]{5}$/.test(w));

    const possibleWords = possibleText
      .split('\n')
      .map(w => w.trim().toUpperCase())
      .filter(w => /^[A-Z]{5}$/.test(w));

    console.log(`Successfully fetched word lists:`);
    console.log(`- Allowed guesses: ${allowedWords.length} words`);
    console.log(`- Possible answers: ${possibleWords.length} words`);

    // We also want to merge both and make sure they are unique
    const allValidGuesses = Array.from(new Set([...allowedWords, ...possibleWords])).sort();

    // Generate src/words.ts
    const content = `// This file is auto-generated by fetch-words.js during build time.
// It contains the complete set of valid Wordle 5-letter words.

export const SECRET_WORDS: string[] = ${JSON.stringify(possibleWords, null, 2)};

export const VALID_GUESSES: string[] = ${JSON.stringify(allValidGuesses, null, 2)};
`;

    const outputPath = path.join(process.cwd(), 'src', 'words.ts');
    fs.writeFileSync(outputPath, content);
    console.log(`Written successfully to ${outputPath}`);
  } catch (error) {
    console.error('Error fetching word lists:', error);
    process.exit(1);
  }
}

fetchWordLists();
